import re

from moekani_2 import wanikani_radical_cards

subradicals = {
    "Enter": ["Person"],
    "Dirt": ["Cross", "Ground"],
    "Sword": ["Power"],
    "Street": ["Ground", "Barb"],
    "Legs": ["Fins"],
}

subs = {
    "Enter": ["Person"],
    "Dirt": ["Cross", "Ground"],
    "Sword": ["Power"],
    "Narwhal": ["Treasure"],
    "Street": ["Barb", "Ground"],
    "Legs": ["Fins"],
    "Thousand": ["Cross", "Slide"],
    "Evening": ["Prison", "Drop"],
    "Child": ["Barb", "Ground"],
    "Small": ["Fins", "Barb"],
    "Heaven": ["Two", "Person"],
    "Hand": ["Barb", "Slide"],
    "Writing": ["Lid", "Stool"],
    "Moon": ["Sun", "Legs"],
    "Stop": ["Toe", "Ground"],
    "Water": ["Barb", "Drop"],
    "Fire": ["Person"],
    "Dog": ["Big"],
    "Middle": ["Mouth"],
    "Book": ["Tree"],
    "White": ["Drop", "Sun"],
    # "Stone": ["Mouth", "Leaf"],
    # "Stand": ["Lid"],
    # "Lion": ["Mouth", "Wide"],
    "Stone": ["Mouth", "Middle", "Nature"],
    "Stand": ["Two", "Lid"],
    "Lion": ["Mouth", "Wide"],
    "Spoon": ["Well", "Person"],
    "Ra": ["Sound", "Well"],
    "Raptor Cage": ["Right", "Well"],
    "Winter": ["Evening", "Early"],
    "Dry": ["Two", "Two", "Well", "Can", "Someone"],
    "Canopy": ["Middle", "Sun"],
    "Fingers": ["Hand", "Few"],
    "Origin": ["Have", "Two", "Legs"],
    "Heart": ["Middle"],
    "Direction": ["Right"],
    "Fur": ["Hair", "Now"],
    "Father": ["Fins", "Treasure", "Right"],
    "Old": ["Cross", "Mouth"],
    "Drawer": ["Two"],
    "Arrow": ["Big", "Small", "Can"],
    "Door": ["Flag", "Ground"],
    "Measurement": ["Have"],
    "Leader": ["Person", "Above", "Not", "Old"],
    "Forehead": ["Part", "Head", "Roof", "Not", "Have"],
    "Alligator": ["See", "Mouth", "Right", "Hand"],
    "Roof": ["Roof"],
    "Ceremony": ["Person", "Wedding", "Have", "See", "Think", "Life"],
    "Branch": ["Cross", "Stool", "Tree", "Life"],
    "Energy": ["See", "Water", "Well"],
    "World": ["Circle", "Big", "Can", "See"],
    "Plate": ["Few", "Together"],
    "Bamboo": ["See"],
    "Thread": ["Small", "Poop"],
    "Poop": ["Private", "Can", "Public", "Next"],
    "Ear": ["Eye", "Become"],
    "Insect": ["Private", "Mouth", "Think", "Friend", "World", "Have"],
    "Flowers": ["See", "Ground", "Not"],
    "See": ["Legs"],
    "Red": ["Legs", "Fins", "Dirt"],
    "Shellfish": ["Giant", "Eye", "Fins"],
    "Foot": ["See", "Right"],
    "Not": ["See", "Think"],
    "Samurai": ["Dirt", "Dirt", "Can", "See", "Think"],
    "Rice": ["Not", "Rice Paddy", "Ground", "See"],
    "Loiter": ["Leader"],
    "Bed": ["Have", "Right", "See"],
    "Tsunami": ["Drop", "Have", "Three", "Number", "Can", "Water", "Go", "Think"],
    "Coffin": ["See", "Slide", "Dirt", "Body"],
    "Wolverine": ["Three", "Hand", "Not", "See"],
    "Twenty": ["Have", "Two", "Together"],
    "Window": ["Cross", "Big", "Can"],
    "Meat": ["Inside", "Head", "Can", "Think", "Sick"],
    "Self": ["Drop", "Eye"],
    "Color": ["Bed", "Prison", "See", "Now", "Bright", "Have"],
    "Go": ["Have", "Loiter", "Two", "Barb", "Someone", "Stop"],
    "West": ["Have", "Pi", "Mouth", "Circle", "Go"],
    "Lip Ring": ["Mouth", "Old", "Times"],
    "Scooter": ["See", "Can", "Stand"],
    "Axe": ["Think", "Cliff", "Think"],
    "Cliff": ["See", "Direction"],
    "Say": ["Sound", "Mouth"],
    "Gold": ["Two", "Protect"],
    "Rain": ["Towel", "Clothes", "Inside"],
    "Blue": ["Have", "Life", "Moon", "Slide", "Well", "Meet", "Right"],
    "Mustache": ["See", "Mouth", "Sweet"],
    "Ice": ["Drop", "Two", "Next", "Water"],
    "Run": ["See", "Person", "Foot", "Head"],
    "Village": ["Rice Paddy", "Dirt", "Have"],
    "Cow": ["Cross", "Stand"],
    "Box": ["Number", "Inside", "Now"],
    "Knife": ["See", "Two", "Well"],
    "Ladle": ["Two", "See", "Part", "Water", "Mouth"],
    "Angel": ["Cross", "Middle", "Someone", "Body"],
    "Boil": ["Fire", "Water"],
    "Yakuza": ["Evening", "Ground", "Night"],
    "Cyclops": ["Head", "Hair", "Big", "Eye", "Middle"],
    "Jet": ["Have", "Nose"],
    "Grain": ["Tree", "Slide", "Rice"],
    "Sheep": ["Above", "See", "Two", "Body"],
    "Blood": ["Plate", "Have", "Not", "Someone", "Stop", "Plate"],
    "Long": ["Have", "Key", "Can"],
    "Eat": ["Go", "White", "Big"],
    "Private": ["Can"],
    "Mama": ["Simple"],
    "Lack": ["Person", "Prison", "Self", "Control"],
    "Fortune": ["Someone", "Toe", "Mouth", "Someone", "Foot"],
    "Stamp": ["Right", "Not"],
    "Husband": ["Ground", "Big", "Jet", "See", "Have"],
    "Clan": ["Cliff", "Cross", "Below", "See"],
    "Spear": ["Right"],
    "Boat": ["Water", "See"],
    "Fish": ["Prison", "Rice Paddy", "Think", "Rice", "Cheap"],
    "Bird": ["See", "Wing", "Head"],
    "Yellow": [
        "Flowers",
        "Ground",
        "Rice Paddy",
        "Fins",
        "Color",
        "Fish",
        "Soul",
        "Flowers",
    ],
    "Black": ["Boil", "Village"],
    "Master": ["King", "Drop", "Water", "Above", "Head", "Not"],
    "Meet": ["Two", "Private", "Have", "Reason", "Not", "Next", "Someone"],
    "Neck": ["Ground", "Attach", "Can", "Now"],
    "Hook": ["Hand", "Pirate", "Have"],
    "Snake": ["Two", "See", "Can", "Head", "Face", "Right", "Mouth", "Now", "Middle"],
    "Cloud": ["See", "Two", "Think"],
    "Weapon": ["Table", "Stool", "Someone", "Now"],
    "Compare": ["Two", "Spoon"],
    "One Sided": ["Half"],
    "Net": ["Water", "Fish", "Can"],
    "Sickle": ["Rice", "Part", "Friend", "See", "Right", "Now", "Grain"],
    "Horse": ["Bird", "Wing", "Have", "Head", "Long", "Neck"],
    "Jammed In": ["Arrow", "Not", "Right"],
    "History": ["Mouth", "Treasure", "Now", "Life", "Person"],
    "Tent": ["Protect", "Can", "Building"],
    "Circumference": ["Dirt", "Head", "Mouth", "Have"],
    "Hole": ["Have", "Roof", "Someone"],
    "Lantern": ["Think", "Old", "Few", "Legs", "Can", "See", "Two", "Angle", "Right"],
    "Easy": ["Sun", "Someone"],
    "Wing": ["See"],
    "Tongue": ["Mouth", "Thousand"],
    "Clown": ["Stand", "Mouth", "Someone"],
    "Building": ["Stand"],
    "Table": ["Legs"],
    "Spicy": ["Cross", "Mouth", "Stand"],
    "Kiss": ["Mouth"],
    "Beans": ["Ground", "Big"],
    "Alcohol": ["Mouth"],
    "Heavy": ["Thousand"],
    "Orders": ["Ground", "Ground"],
    "Temple": ["Hill", "Think", "Have"],
    "Escalator": ["Stairs"],
    "Drunkard": ["Slide"],
    "Root": ["Sun", "Ground"],
    "Simple": ["Cross"],
    "Asia": ["Ground"],
    "Yoga": ["Someone", "Sound"],
    "Jackhammer": ["Barb", "Two"],
    "Excuse": ["Sun", "Prison"],
    "Life": ["Cow", "Ground", "Slide", "Part", "Both"],
    "Umbrella": ["See", "Think"],
    "Death": ["Lid", "Lion", "Meet", "Think", "Long"],
    "Feathers": ["Right", "Well"],
    "Gate": ["Right", "Big", "Two", "Above", "Can"],
    "Suit": ["Ground", "Mouth", "Think", "Well", "Feeling", "Not"],
    "Cage": ["Door", "Gate", "Nothing", "Inside"],
    "Bundle": ["Tree"],
    "Brush": ["Head", "See"],
    "Womb": ["Two", "Ground"],
    "Oneself": ["Self", "Mix"],
    "Original": ["Can"],
    "Center": ["Someone", "Big", "Head", "Have", "Right"],
    "Soul": ["Fins", "Body"],
    "Pig": ["Have", "Ground", "See", "Can", "Legs", "Right"],
    "Fruit": ["Tree"],
    "Pool": ["Drop", "Prison"],
    "Now": ["Ra", "Ra", "Right"],
    "Turkey": ["Mouth"],
    "Saw": ["Drop"],
    "Paragraph": ["Mouth", "Prison", "Well"],
    "Man": ["Rice Paddy", "Power", "Big", "Next", "Rice Paddy", "Rice"],
    "Face": ["Mouth", "Well"],
    "Good Luck": ["Mouth"],
    "Tiger": ["Seven"],
    "Poem": ["Paragraph"],
    "Gambler": ["Cross", "Two", "Big"],
    "Mask": ["Big", "Mouth"],
    "Black Hole": ["Sun", "Become"],
    "Mona Lisa": ["Can"],
    "Ego": ["Drunkard"],
    "Flood": ["River", "Water"],
    "Mole": ["Dirt", "Ground"],
    "Mohawk": ["Head"],
    "Simultaneous": ["Writing", "Moon", "Can", "Someone"],
    "Bathtub": ["Head"],
    "Dollar": ["Two", "Well"],
    "Allocate": ["Legs", "Can"],
    "Football": ["Ground"],
    "Leather": ["Body", "Head"],
    "Vines": ["Two", "Together"],
    "Restaurant": ["Lid", "Street", "Mouth"],
    "Demon": ["Can", "Face"],
    "Dawn": ["Sun", "Ground", "Can", "Sun"],
    "Korea": ["Five", "Cow", "Five"],
    "Wedding": ["Someone", "Eye", "Person", "Big", "Happiness"],
    "Lifeguard": ["Two"],
    "Rake": ["Can"],
    "Giant": ["Head", "Two", "Right"],
    "Barracks": ["Big", "Slide"],
    "Hercules": ["Sword", "Well"],
    "Lovely": ["Two", "Mouth", "Nothing"],
    "Charcoal": ["Sun", "Small", "Big", "Fire"],
    "Clothes": ["Right"],
    "Servant": ["Giant"],
    "Nose": ["Right", "Eye"],
    "Odd": ["Big"],
    "Lineage": ["Ground", "Dirt", "Hand"],
    "Call": ["Sword", "Mouth", "Someone", "Right", "Can"],
    "Fang": ["Mouth", "Can", "Can"],
    "Bully": ["Someone"],
    "Rocket": ["Lid", "Treasure", "Part", "Private", "Head"],
    "Library": ["Door"],
    "Cat Pirate": ["Pirate"],
    "Receive": ["Lid", "Mouth", "Child"],
    "Storehouse": ["Become", "Water", "Can"],
    "Catapult": ["Legs", "Can"],
    "Slice": ["Half", "Person"],
    "Turtle": ["Turtle Shell", "Inside", "Can", "Head"],
    "Shuriken": ["Ground"],
    "Sake": ["Big", "Call"],
    "Greenhouse": ["Sun", "Big"],
    "Sweet": ["Sun", "Hair", "Stand"],
    "Omen": ["Legs"],
    "Hot Pepper": ["Flag", "Mouth"],
    "Signpost": ["Winter", "North"],
    "Righteousness": ["King", "Ego", "Big"],
    "Melon": ["Half", "See", "Private", "Not"],
    "Grenade": ["Middle"],
    "Shop": ["Have", "Roof"],
    "Plow": ["Dirt", "Tree"],
    "Imperial": ["Stand", "Moon", "Can"],
    "Pirate": ["Big"],
    "Blade": ["Sword", "Drop", "Someone", "Sword"],
    "Dragon": ["Turtle"],
    "Wrap": ["Prison"],
    "House": ["Roof", "Pig", "Inside", "Member"],
    "Mysterious": ["Lid"],
    "Crab Trap": ["Small", "Animal", "Crab", "Inside"],
    "Height": ["Slide"],
    "Splinter": ["Turtle Shell", "Mustache", "Giant"],
    "Badger": ["Animal", "Have"],
    "Teacher": ["Coffin", "Child", "Not", "Dance"],
    "Coat Rack": ["See"],
    "Drum": ["Beans", "Can"],
    "Guard": ["Older Brother", "Part"],
    "Helicopter": ["Can", "See", "Part", "Big", "Blade"],
    "Mantis": ["Slide", "Head"],
    "Frostbite": ["Dirt", "Legs", "Winter", "Have"],
    "Spider": ["Can", "Private", "Legs", "Winter"],
    "Boot": ["Leather", "Dirt"],
    "Dance": ["Cow", "Evening", "Can"],
    "Nurse": ["Clothes", "Six", "Same", "Together", "Have", "Change"],
    "Penguin": ["Fins", "Towel", "Winter"],
    "Cottage": ["Middle", "Mountain", "Roof", "Door"],
    "Concave": ["Hole"],
}


# Used these to find a list of mentioned radicals, then corrected the list manually
def find_same_as_kanji_radicals(radical_cards):
    return [
        card["Radical_Name"]
        for card in filter(
            lambda card: "the same as the kanji".lower()
            in card["Radical_Mnemonic"].lower(),
            radical_cards,
        )
    ]


def generate_subradical_list(radical_cards):
    subradical_dict = {}
    same_as_kanji_radicals = find_same_as_kanji_radicals(radical_cards)
    for radical_card in radical_cards:
        if radical_card["Radical_Name"] in same_as_kanji_radicals:
            continue

        radical_names = [card["Radical_Name"] for card in radical_cards]
        radical_names.remove(radical_card["Radical_Name"])

        pattern = r"\b(?:" + "|".join(map(re.escape, radical_names)) + r")\b"
        matches = re.findall(
            pattern, radical_card["Radical_Mnemonic"], flags=re.IGNORECASE
        )

        matches_unique = list(dict.fromkeys(matches))
        matches_unique_casefixed = [
            next(
                radical_name
                for radical_name in radical_names
                if radical_name.lower() == match.lower()
            )
            for match in matches_unique
        ]

        matched_cards = [
            next(card for card in radical_cards if card["Radical_Name"] == match)
            for match in matches_unique_casefixed
        ]

        # If the found match is of a higher level, it must be a coincidental match - disregard match
        for matched_card in matched_cards:
            if matched_card["Wanikani_Level"] > radical_card["Wanikani_Level"]:
                matches_unique_casefixed.remove(matched_card["Radical_Name"])

        if len(matches_unique_casefixed) > 0:
            subradical_dict[radical_card["Radical_Name"]] = matches_unique_casefixed

    print(subradical_dict)


generate_subradical_list(wanikani_radical_cards)

{
    "id": 8766,
    "object": "radical",
    "url": "https://api.wanikani.com/v2/subjects/8766",
    "data_updated_at": "2024-12-20T03:28:45.416907Z",
    "data": {
        "created_at": "2012-03-01T21:30:51.000000Z",
        "level": 4,
        "slug": "beggar",
        "hidden_at": None,
        "document_url": "https://www.wanikani.com/radicals/beggar",
        "characters": None,
        "character_images": [
            {
                "url": "https://files.wanikani.com/a5hm25g0yev9mmabgx56q8b1xao3",
                "metadata": {
                    "color": "#000000",
                    "dimensions": "1024x1024",
                    "style_name": "original",
                },
                "content_type": "image/png",
            },
            {
                "url": "https://files.wanikani.com/p6of5uhr8tbg3d40tkz7vcm73xhe",
                "metadata": {
                    "color": "#000000",
                    "dimensions": "1024x1024",
                    "style_name": "1024px",
                },
                "content_type": "image/png",
            },
            {
                "url": "https://files.wanikani.com/60d5xb33cykph9lvf7qvwop5c78x",
                "metadata": {
                    "color": "#000000",
                    "dimensions": "512x512",
                    "style_name": "512px",
                },
                "content_type": "image/png",
            },
            {
                "url": "https://files.wanikani.com/2m3rommgcd460nk03dd26gg7xzvu",
                "metadata": {
                    "color": "#000000",
                    "dimensions": "256x256",
                    "style_name": "256px",
                },
                "content_type": "image/png",
            },
            {
                "url": "https://files.wanikani.com/3w7owodc1sryl4lgnvai0fr0uvgj",
                "metadata": {
                    "color": "#000000",
                    "dimensions": "128x128",
                    "style_name": "128px",
                },
                "content_type": "image/png",
            },
            {
                "url": "https://files.wanikani.com/s8n8dq3lta5n5tlhw43s8o8tqdmg",
                "metadata": {
                    "color": "#000000",
                    "dimensions": "64x64",
                    "style_name": "64px",
                },
                "content_type": "image/png",
            },
            {
                "url": "https://files.wanikani.com/g5y5yjbcc5a92hsfwef8rqjnfh34",
                "metadata": {
                    "color": "#000000",
                    "dimensions": "32x32",
                    "style_name": "32px",
                },
                "content_type": "image/png",
            },
            {
                "url": "https://files.wanikani.com/8v0hjy2gh2dnmh1cgbcg8cedpd58",
                "metadata": {"inline_styles": True},
                "content_type": "image/svg+xml",
            },
        ],
        "meanings": [{"meaning": "Beggar", "primary": True, "accepted_answer": True}],
        "auxiliary_meanings": [],
        "amalgamation_subject_ids": [531, 576, 1249, 2443],
        "meaning_mnemonic": "Doesn't this look like someone on their knees, holding their hands out (clasped) and begging for something (money, their life, etc.)? That's why this radical is known as the <radical>beggar</radical>.",
        "lesson_position": 37,
        "spaced_repetition_system_id": 1,
    },
}
